platform :ios, '7.0'
inhibit_all_warnings!

def pods
  pod 'AFNetworking'
  pod 'NYXImagesKit'
  pod 'FXKeychain'
  pod 'BlocksKit'
  pod 'NSString-Hashes'
  pod 'FrameAccessor'
  pod 'MWFeedParser'
  pod 'RegexKitLite'
  pod 'MBProgressHUD'
end

  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ARCHS'] = 'armv7 arm64'
          end
      end
  end

target "babysay" do
  pods
end